### ISSUE TITLE
intl dependencies

### ISSUE THREAD

**Issue by fvisticot** [Zsmerritt/Flutter_AWS_Request#1]
intl 0.17.0 is required for recent packages.
Can you please update intl to 0.17.0 ?

**Comment by Zsmerritt** [comment]
Ill be working on an update for null safety sometime this week or weekend that updates all the packages to their current versions

**Comment by Zsmerritt** [comment]
Just published a new release version 0.1.0 that supports intl 0.17.0 and crypto 3.0.0
