### ISSUE TITLE
getAuth parameters null check

### ISSUE THREAD

**Issue by zokonil** [Zsmerritt/Flutter_AWS_Request#5]
../flutter/.pub-cache/hosted/pub.dartlang.org/aws_request-0.1.4/lib/aws_request.dart:253:62: Error: The argument type 'String?' can't be assigned to the parameter type 'String' because 'String?' is nullable and 'String' isn't.
          String auth = _getAuth(amzDate, canonicalRequest, this._region);
          
_region is defined as String? but the _getAuth function is excepting String as a input, thus throwing out this error

Could you please add a check for the region parameter or change its type?

**Comment by Zsmerritt** [comment]
Should be fixed in latest release v0.1.5  
 Thanks for letting me know and let me know if you run into anything else :)
